#!/bin/sh

rm -rf .git
rm -f .gitignore
rm -rf .vscode
rm -f browserui.js
rm -rf completed.html
rm -f config.html
rm -f coverage
rm -rf dist
rm -f index.html
rm -f index.ts
rm -rf lib
rm -f Makefile
rm -rf node_modules
rm -f package.json
rm -f package-lock.json
rm -f papers.md
rm -rf pics
rm -f posttest.html
rm -f pretest.html
rm -f README.md
rm -f style.css
rm -f swell-paper.md
rm -rf test
rm -f tsconfig.json
rm -rf tutorials
rm -rf ui_modules
rm -f weekly-and-lesson-plans.md
rm -f welcome.html
rm -rf wireframes
rm -f deleteme.sh
